name: simple_query
version: 1.0.0
description: Optimized workflow for simple database queries

steps:
  - name: classify_query
    type: simple_classifier
    patterns:
      count: ["how many", "count", "number of"]
      find: ["show", "list", "get", "find"]
      aggregate: ["sum", "average", "group", "total"]
    default_tool: mongodb_count
    
  - name: execute_query
    type: conditional
    condition: $steps.classify_query.type
    cases:
      count:
        type: tool
        tool: mongodb_count
        params:
          collection: $classification.collection
          filter: $classification.filter
      find:
        type: tool
        tool: mongodb_find
        params:
          collection: $classification.collection
          filter: $classification.filter
          limit: 10
      aggregate:
        type: tool
        tool: mongodb_aggregate
        params:
          collection: $classification.collection
          pipeline: $classification.pipeline
    default:
      type: tool
      tool: mongodb_count
      params:
        collection: "users"
        filter: {}
    critical: true
    
  - name: format_response
    type: simple_formatter
    template: "Query result: {result}"
    data: $steps.execute_query