apiVersion: v1
kind: ConfigMap
metadata:
  name: hydrogen-config
  namespace: hydrogen-ai
data:
  LOG_LEVEL: "INFO"
  REDIS_URL: "redis://redis-service:6379"
  EVENT_BUS_URL: "nats://nats-service:4222"
  MCP_SERVER_URL: "http://mcp-server-service:8000"
  PLUGIN_DIR: "/app/plugins"
  CONFIG_DIR: "/app/config"
  SCHEMA_CACHE_TTL: "3600"
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: "5"
  CIRCUIT_BREAKER_RECOVERY_TIMEOUT: "30"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-configs
  namespace: hydrogen-ai
data:
  schema_discovery.yaml: |
    name: schema_discovery
    version: 1.0.0
    description: Agents for discovering database schema
    
    agents:
      - name: collection_inspector
        role: Collection Inspector
        goal: List all collections in the database
        backstory: A meticulous inspector that finds every collection
        tools:
          - mongodb_list_collections
        
      - name: schema_profiler
        role: Schema Profiler
        goal: Sample documents and profile the schema for each collection
        backstory: A data scientist who understands data structures
        tools:
          - mongodb_find
          
      - name: relationship_mapper
        role: Relationship Mapper
        goal: Analyze schemas to find foreign key relationships
        backstory: A data architect who uncovers hidden connections
        tools:
          - mongodb_get_indexes