apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hydrogen-prod

bases:
  - ../../base

patchesStrategicMerge:
  - patches/deployment-patches.yaml
  - patches/service-patches.yaml
  - patches/hpa.yaml

configMapGenerator:
  - name: hydrogen-config-prod
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
      - SCHEMA_CACHE_TTL=86400
      - CIRCUIT_BREAKER_FAILURE_THRESHOLD=3
      - CIRCUIT_BREAKER_RECOVERY_TIMEOUT=60

replicas:
  - name: orchestrator
    count: 3
  - name: mcp-server
    count: 2
  - name: kong
    count: 2

resources:
  - ingress-prod.yaml
  - pdb.yaml
  - network-policies.yaml