name: query_planning
version: 1.0.0
description: Agents for planning and building queries

agents:
  - name: query_planner
    role: Query Planning Manager
    goal: Analyze user queries and create optimal execution plans
    backstory: A strategic thinker who understands both structured and unstructured data
    tools:
      - analyze_query_intent
      - get_schema_info
    max_iterations: 3
    
  - name: pipeline_builder
    role: Pipeline Builder
    goal: Construct MongoDB aggregation pipelines from query plans
    backstory: A data engineer expert in MongoDB aggregations
    tools:
      - build_match_stage
      - build_group_stage
      - build_sort_stage
      - build_project_stage
    
  - name: join_specialist
    role: Join Specialist
    goal: Handle complex joins between collections
    backstory: A specialist in database relationships and lookups
    tools:
      - build_lookup_stage
      - optimize_join_order
    
  - name: query_validator
    role: Query Validator
    goal: Validate and optimize final queries
    backstory: A perfectionist who ensures queries are correct and efficient
    tools:
      - validate_pipeline
      - estimate_performance

tasks:
  - name: analyze_query
    agent: query_planner
    description: Analyze the user's query and determine the best approach
    expected_output: Query execution plan with approach (aggregation/RAG/simple)
    
  - name: build_pipeline
    agent: pipeline_builder
    description: Build the main aggregation pipeline stages
    dependencies: [analyze_query]
    expected_output: List of MongoDB aggregation stages
    
  - name: add_joins
    agent: join_specialist
    description: Add necessary lookup stages for joins
    dependencies: [build_pipeline]
    expected_output: Complete pipeline with lookups
    
  - name: validate_query
    agent: query_validator
    description: Validate and optimize the final query
    dependencies: [add_joins]
    expected_output: Validated and optimized MongoDB pipeline